apps/profiles/urls.py
# from django.conf.urls.defaults import *
# 
# from idios.views import ProfileListView, ProfileDetailView, ProfileUpdateView
# 
# 
# urlpatterns = patterns("idios.views",
#     url(r"^(?P<username>[\w\._-]+)/$", ProfileDetailView.as_view(), name="profile_detail"),
#     url(r"^(?P<profile_slug>[\w\._-]+)/up/(?P<profile_pk>\d+)/$", ProfileDetailView.as_view(), name="profile_detail"),
#     
#     # url(r"^edit/(?P<username>[\w\._-]+)$", ProfileUpdateView.as_view(), name="profile_edit"),
#     
#     # url(r"^all/$", ProfileListView.as_view(all_profiles=True), 
#     #         name="profile_list_all"),
#     url(r"", include("idios.urls_base")),
#     url(r"^(?P<profile_slug>[\w\._-]+)/", include("idios.urls_base")),
# )

from django.conf.urls.defaults import *
from idios.views import ProfileListView, ProfileDetailView, ProfileUpdateView

# for squad.xml and squad.dtd generation - took view code from idios.views
from django.views.generic.detail import DetailView
from itwishlist.apps.profiles.views import SquadXMLView
from itwishlist.apps.profiles.models import Profile
from django.views.generic.simple import direct_to_template

urlpatterns = patterns("idios.views",
    
    # disabling ability to view list of all user profiles
    url(r"^$", ProfileListView.as_view(all_profiles=True), name="profile_list_all"),
    
    # url(r"^(?P<profile_slug>[\w\._-]+)/", include("idios.urls_base")),
    # url(r"^(?P<profile_slug>[\w\._-]+)/(?P<profile_pk>\d+)/$", ProfileDetailView.as_view(), name="profile_detail"),
    # url(r"", include("idios.urls_base")),
    
    url(r"^(?P<username>[\w\._-]+)/$", ProfileDetailView.as_view(), name="profile_detail"),
    url(r"^edit/(?P<username>[\w\._-]+)$", ProfileUpdateView.as_view(), name="profile_edit"),
)

# for squad.xml and squad.dtd generation - took view code from idios.views
urlpatterns += patterns("itwishlist.apps.profiles.views",
    url(r"^(?P<username>[\w\._-]+)/squad.dtd$", direct_to_template, {"template": "profiles/squad.dtd",}, name="squaddtd"),
    url(r"^(?P<username>[\w\._-]+)/squad.xml$", SquadXMLView.as_view(), name="squadxml"),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.views.generic.date_based import archive_index
from itwishlist.apps.blog import views
from django.contrib import admin
admin.autodiscover()
from pinax.apps.account.openid_consumer import PinaxConsumer

handler500 = "pinax.views.server_error"

from itwishlist.apps.blog.feeds import BlogFeedUser
blogs_feed_dict = {"feed_dict": {
    'only': BlogFeedUser,
    }}

from itwishlist.apps.blog.models import Post, IS_PUBLIC
post_dict_public = {
    'queryset': Post.objects.filter(status=IS_PUBLIC),
    'template_object_name': 'post',
}
post_dict = {
    'queryset': Post.objects.filter(),
    'template_object_name': 'post',
}

# =todo: vanity url: http://stackoverflow.com/questions/3333765/get-user-from-url-segment-with-django 

urlpatterns = patterns("",

    url(r"^$", "itwishlist.apps.blog.views.homepage", name="home"),
    url(r"^new/$", "itwishlist.apps.blog.views.new", name="new"),

    url(r"^bug/$", "itwishlist.apps.blog.views.bug", name="bug"),
    url(r"^feature/$", "itwishlist.apps.blog.views.feature", name="feature"),
    url(r"^done/$", "itwishlist.apps.blog.views.done", name="done"),
    url(r"^inprogress/$", "itwishlist.apps.blog.views.inprogress", name="inprogress"),
    url(r"^kb/$", "itwishlist.apps.blog.views.kb", name="kb"),
    
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    # url(r"^about/", include("about.urls")),
    # url(r"^faq/$", direct_to_template, {"template": "faq.html"}, name="faq"),
    
    # =todo: authenticate against drupal users db
    # url(r'^sso/$', 'django.contrib.auth.views.login'),
    
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
    url(r"^profiles/", include("profiles.urls")), # NOTA BENE: that this is pointing to profiles/urls.py and not IDIOS app...
    # url(r"^up/", include("profiles.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^announcements/", include("announcements.urls")),
    # url(r'^log/', include('blog.urls')),
    url(r'^posts/', include('itwishlist.apps.blog.urls')),
    url(r'^relationships/', include('relationships.urls')),
    url(r'^following/','itwishlist.apps.blog.views.following', name='following'),
    url(r'^followers/','itwishlist.apps.blog.views.followers', name='followers'),
    url(r'^backup/$', 'itwishlist.apps.blog.views.backup', name='backup'),
    url(r'^desk/$', 'itwishlist.apps.blog.views.desk', dict(post_dict, template_name='blog/desk.html'), name='desk'),
    url(r'^post/$', 'itwishlist.apps.blog.views.add', name='blog_add'),
    # url(r'^b/', include('blogs.short_urls')), # For short urls, if you want
    url(r'^feeds/posts/(?P<url>w+)/', 'django.contrib.syndication.views.feed', blogs_feed_dict),
    # todo: upgrade to django 1.4
    # url(r'^feeds/posts/(?P<url>w+)/', 'django.contrib.syndication.views.Feed', blogs_feed_dict),
    url(r'^search/$', 'itwishlist.apps.blog.views.search', name="search"),
    url(r'^files/', include('itwishlist.apps.fileupload.urls')),
    )

# urlpatterns += patterns('django.views.generic.simple',
#     url(r'^about/$', 'direct_to_template', {'template': 'about.html'}, name='about'),
# )


# if settings.SERVE_MEDIA:
#     urlpatterns += patterns("",
#         url(r"", include("staticfiles.urls")),
#     )

# =todo: figure out why I had to add this so player image is served
if settings.DEBUG :
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
        url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

apps/profiles/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from idios.models import ProfileBase

from datetime import datetime

# from imagekit.models.fields import ProcessedImageField
# from imagekit.models import ImageSpecField
# from imagekit.processors import ResizeToFill
from easy_thumbnails.fields import ThumbnailerImageField

class Profile(ProfileBase):
    name = models.CharField(_("Name"), max_length=50, null=True, blank=True, help_text="Your it.ippc.int byline (best to use your real name unless you want to confuse people :)")
    # email = models.EmailField(_("Email"), blank=True, help_text="An email address you want to display publically.")
    # im = models.CharField(_("im"), max_length=50, null=True, blank=True, help_text="An instant messaging handle you want to display publically.")
    # url = models.URLField(blank=True, null=True, help_text="A URL you may want to share?")
    # remark = models.TextField(_("remark"), null=True, blank=True, help_text="Any remarks you would like to share?")
    user_photo = models.ImageField(_("Image"), upload_to="user_photo/%Y/%m/%d/", blank=True, help_text="Will be resized to 260x180 pixels, if larger.") # no player images yet
    # user_photo = ProcessedImageField(_("Image"), upload_to="user_photo/%Y/%m/%d/", blank=True) # no player images yet
    # player_thumb = ImageSpecField([ResizeToFill(260, 180)], format="JPEG", options={"quality": 75})
    date_joined = models.DateTimeField(_("Member Since"), default=datetime.now, editable=False)
    

# class ProfileForm(ModelForm):
#     class Meta:
#         model = Profile
#         # fields = ('name', 'player_id', 'email', 'im', 'remark',)
#         exclude = ("user_photo", "email",)

apps/profiles/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

try:
    from django.views.generic import ListView, DetailView, CreateView, UpdateView
except ImportError:
    try:
        from cbv import ListView, DetailView, CreateView, UpdateView
    except ImportError:
        raise ImportError(
            "It appears you are running a version of Django < "
            "1.3. To use idios with this version of Django, install "
            "django-cbv==0.1.5."
        )

from idios.utils import get_profile_model, get_profile_base

if "notification" in settings.INSTALLED_APPS:
    from notification import models as notification
else:
    notification = None

def group_and_bridge(kwargs):
    """
    Given kwargs from the view (with view specific keys popped) pull out the
    bridge and fetch group from database.
    """

    bridge = kwargs.pop("bridge", None)

    if bridge:
        try:
            group = bridge.get_group(**kwargs)
        except ObjectDoesNotExist:
            raise Http404
    else:
        group = None

    return group, bridge


def group_context(group, bridge):
    # @@@ use bridge
    return {
        "group": group,
    }


class SquadXMLView(DetailView):

    template_name = "profiles/squad.xml"
    context_object_name = "profile"

    def get_object(self):

        username = self.kwargs.get("username")
        profile_class = get_profile_model(self.kwargs.get("profile_slug"))

        if profile_class is None:
            raise Http404

        if username:
            self.page_user = get_object_or_404(User, username=username)
            return get_object_or_404(profile_class, user=self.page_user)
        else:
            profile = get_object_or_404(
                profile_class, pk=self.kwargs.get("profile_pk")
            )
            self.page_user = profile.user
            return profile

    def get_context_data(self, **kwargs):

        base_profile_class = get_profile_base()
        profiles = base_profile_class.objects.filter(user=self.page_user)

        group, bridge = group_and_bridge(kwargs)
        is_me = self.request.user == self.page_user

        ctx = group_context(group, bridge)
        ctx.update({
            "is_me": is_me,
            "page_user": self.page_user,
            "profiles": profiles,
        })
        ctx.update(
            super(SquadXMLView, self).get_context_data(**kwargs)
        )

        return ctx




# =todo: authenticate against drupal users db
# http://chirale.wordpress.com/2013/03/15/unified-login-in-django-and-drupal/
# from django.contrib.auth.decorators import login_required
# from django.conf import settings
# import subprocess
# 
# @login_required
# def sso(request):
#    try:
#        assert request.user.drupal_id > 0
#        # user id to log in
#        drupal_id = str(request.user.drupal_id)
#        output = ""
#        try:
#            # DRUPAL_SITE_PATH is the absolute path to Drupal installation
#            # DRUPAL_SITE_NAME is the Drupal site name, e.g. example.com
#            output = check_output(["drush", "-r", settings.DRUPAL_SITE_PATH, "-l", settings.DRUPAL_SITE_NAME, "user-login", drupal_id])
#        except CalledProcessError:
#            # @todo add additional control statement?
#            pass
#        if output:
#            # Declare DRUPAL_SITE_URL on settings.py and set it as 'www.example.com'
#            #     your Drupal site name
#            drupal_login_url = output.replace("http://ippcdrupal.dev/", "http://%s/" % settings.DRUPAL_SITE_URL).strip()
#            # set Drupal login destination using DRUPAL_LOGIN_DESTINATION
#            destination = "%s?destination=%s" % (drupal_login_url, settings.DRUPAL_LOGIN_DESTINATION)
#            return redirect(destination)
#        else:
#            # no output from the drush command
#            return HttpResponse('Wrong request')
#    except AssertionError:
#        # Drupal id is not assigned
#        return HttpResponse('Not registered user')

templates/idios/_profile_form.html
{% load i18n %}
{% load bootstrap_tags %}
{% load url from future %}

{% if profile_form.is_multipart %}
    {# <form class="customform" method="POST" enctype="multipart/form-data" action="{% url "profile_edit" %}"> #}
    <form class="customform" method="POST" enctype="multipart/form-data" action="/profiles/edit/{{profile.user.username}}">
{% else %}
    <form class="customform" method="POST" enctype="multipart/form-data" action="/profiles/edit/{{profile.user.username}}">
{% endif %}
    <legend>Edit Profile</legend>  
    {% csrf_token %}
    {{ profile_form|as_bootstrap }}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">{% trans "Update" %}</button> or <a href="{% url "profile_detail" profile.user.username %}">{% trans "Cancel" %}</a>
    </div>
</form>

{# Help to find player id #}
{% comment %}

<div class="modal hide" id="help">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Help</h3>
  </div>
<div class="modal-body">
<h4>How to Find Your Rome In-Game Player ID</h4>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<h4>How to Find Your Rome In-Game Player Username</h4>

 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    {# <a href="#" class="btn btn-primary">Save changes</a> #}
  </div>
</div>
{% endcomment %}

templates/idios/additional_info.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap_tags %}

{% block head_title %}{% trans "Additional Info" %}{% endblock %}

{% block body %}
    <header class="jumbotron subhead" id="overview">
        <h1>{% trans "Additional Info" %}</h1>
        <p class="lead">{% blocktrans %}Please fill out the following form so we know a little about you.{% endblocktrans %}</p>
    </header>
    
    <form method="POST" action="">
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
        </div>
    </form>
{% endblock %}

templates/idios/base.html
{% extends "subnav_base.html" %}

{% load i18n %}
{% load url from future %}

{% block subnav %}
    {% if user.is_authenticated %}
        <ul class="nav nav-list">
            <li class="nav-header">{% trans "Profile" %}</li>
            <li><a href="{% url "profile_detail" user.username %}">{% trans "My Profile" %}</a></li>
            <li><a href="{% url "profile_list" %}">{% trans "All Profiles" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

templates/idios/profile.html
{% extends "idios/base.html" %}

{% load i18n %}
{% load account_tags %}
{% load url from future %}

{% block head_title %}{{ profile.name }} - Profile{% endblock %}

{% block body_id %}profile{% endblock %}

{% block body %}
{#     {% user_display page_user as page_user_display %} #}
{# <div class="hero-unit well"> #}
{#         <h1>{{ profile.name }}</h1> #}
{# </div> #}
    
    {% include "profiles/_profile_info.html" %}
    
    {% if is_me %}
        {# <p><a href="{% url "profile_edit" %}" class="btn">{% trans "Update my profile" %}</a></p> #}
        {# <p><a href="/up/edit/{{user}}" class="btn">{% trans "Update my profile" %}</a></p> #}
    {% endif %}
{% endblock %}

templates/idios/profile_edit.html
{% extends "idios/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Edit Profile" %}{% endblock %}

{% block body %}
    
    {% include "idios/_profile_form.html" %}
    
{% endblock %}

templates/idios/profile_edit_ajax.html
{% load bootstrap_tags %}
{% load i18n %}
{% load url from future %}

<form class="ajax modal-form" method="POST" action="{% url "profile_edit" %}">
    <div class="modal-header">
        <h3>{% trans "Edit Profile" %}</h3>
        {# <a href="#" class="close modal-close">&times;</a> #}
    </div>
    
    <div class="modal-body">
        {% csrf_token %}
        {{ profile_form|as_bootstrap }}
    </div>
    
    <div class="modal-footer">
        <a href="#" class="btn modal-close">{% trans "Cancel" %}</a>
        <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
    </div>
</form>

templates/idios/profile_edit_ajax_success.html
{% load i18n %}

<div class="modal-header">
    <h3>{% trans "Success!" %}</h3>
    <a href="#" class="close modal-close">&times;</a>
</div>

<div class="modal-body">
    <p>{% trans "Your profile has been successfully updated!" %}</p>
</div>

<div class="modal-footer">
    <a href="#" class="btn btn-primary modal-close">{% trans "Close" %}</a>
</div>

templates/idios/profiles.html
{% extends "idios/base.html" %}

{% load account_tags %}
{% load pagination_tags %}

{% block head_title %}All Profiles{% endblock %}

{% block body %}

{# <p class="breadcrumb"> #}
{#     <a href="/">Home</a> / Profiles #}
{# </p> #}

    <header class="jumbotron subhead" id="overview">
        <h1>All Profiles</h1>
        <p class="lead">User profiles in it.ippc.int</p>
    </header>

    <table class="table table-striped table-condensed">
        <thead>
        <tr>
            <th>User Profile Page</th>
            <th>Member Since</th>
            <th>User Items Home</th>
        </tr>
        </thead>
        <tbody>
    {% autopaginate profiles %}
    
    {% for profile in profiles %}
        {% include "profiles/_profile_item.html" %}
    {% endfor %}
    
    {% paginate %}
        </tbody>
    </table>
{% endblock %}